using Counseling.Entity.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Counseling.Data.Concrete.Config
{
    public class UniversityConfig : IEntityTypeConfiguration<University>
    {
        public void Configure(EntityTypeBuilder<University> builder)
        {
            builder.HasKey(x => x.Id);
            builder.Property(x => x.Id).ValueGeneratedOnAdd();
            builder.Property(x => x.Name).IsRequired().HasMaxLength(50);
            builder.HasData(
                new University { Id = 1, Name = "Adana Alparslan Türkeş Bilim ve Teknoloji Üniversitesi" },
                new University { Id = 2, Name = "Adana Bilim ve Teknoloji Üniversitesi" },
                new University { Id = 3, Name = "Adıyaman Üniversitesi" },
                new University { Id = 4, Name = "Afyonkarahisar Sağlık Bilimleri Üniversitesi" },
                new University { Id = 5, Name = "Afyonkarahisar Sandıklı Onmyo Meslek Yüksekokulu" },
                new University { Id = 6, Name = "Ağrı İbrahim Çeçen Üniversitesi" },
                new University { Id = 7, Name = "Ahi Evran Üniversitesi" },
                new University { Id = 8, Name = "Akdeniz Üniversitesi" },
                new University { Id = 9, Name = "Aksaray Üniversitesi" },
                new University { Id = 10, Name = "Alanya Alaaddin Keykubat Üniversitesi" },
                new University { Id = 11, Name = "Altınbaş Üniversitesi" },
                new University { Id = 12, Name = "Amasya Üniversitesi" },
                new University { Id = 13, Name = "Anadolu Üniversitesi" },
                new University { Id = 14, Name = "Ankara Hacı Bayram Veli Üniversitesi" },
                new University { Id = 15, Name = "Ankara Üniversitesi" },
                new University { Id = 16, Name = "Ankara Yıldırım Beyazıt Üniversitesi" },
                new University { Id = 17, Name = "Antalya Akev Üniversitesi" },
                new University { Id = 18, Name = "Antalya Bilim Üniversitesi" },
                new University { Id = 19, Name = "Arda Üniversitesi" },
                new University { Id = 20, Name = "Ardahan Üniversitesi" },
                new University { Id = 21, Name = "Artvin Çoruh Üniversitesi" },
                new University { Id = 22, Name = "Atatürk Üniversitesi" },
                new University { Id = 23, Name = "Avrasya Üniversitesi" },
                new University { Id = 24, Name = "Aydın Adnan Menderes Üniversitesi" },
                new University { Id = 25, Name = "Aydın Üniversitesi" },
                new University { Id = 26, Name = "Bahçeşehir Üniversitesi" },
                new University { Id = 27, Name = "Balıkesir Üniversitesi" },
                new University { Id = 28, Name = "Bandırma Onyedi Eylül Üniversitesi" },
                new University { Id = 29, Name = "Bartın Üniversitesi" },
                new University { Id = 30, Name = "Batman Üniversitesi" },
                new University { Id = 31, Name = "Beykent Üniversitesi" },
                new University { Id = 32, Name = "Bilecik Şeyh Edebali Üniversitesi" },
                new University { Id = 33, Name = "Bingöl Üniversitesi" },
                new University { Id = 34, Name = "Bursa Orhangazi Üniversitesi" },
                new University { Id = 35, Name = "Bursa Teknik Üniversitesi" },
                new University { Id = 36, Name = "Çağ Üniversitesi" },
                new University { Id = 37, Name = "Çankaya Üniversitesi" },
                new University { Id = 38, Name = "Çanakkale Onsekiz Mart Üniversitesi" },
                new University { Id = 39, Name = "Çankırı Karatekin Üniversitesi" },
                new University { Id = 40, Name = "Çukurova Üniversitesi" },
                new University { Id = 41, Name = "Dicle Üniversitesi" },
                new University { Id = 42, Name = "Dokuz Eylül Üniversitesi" },
                new University { Id = 43, Name = "Dumlupınar Üniversitesi" },
                new University { Id = 44, Name = "Düzce Üniversitesi" },
                new University { Id = 45, Name = "Ege Üniversitesi" },
                new University { Id = 46, Name = "Erciyes Üniversitesi" },
                new University { Id = 47, Name = "Erzincan Üniversitesi" },
                new University { Id = 48, Name = "Erzurum Atatürk Üniversitesi" },
                new University { Id = 49, Name = "Erzurum Teknik Üniversitesi" },
                new University { Id = 50, Name = "Eskişehir Osmangazi Üniversitesi" },
                new University { Id = 51, Name = "Eskişehir Teknik Üniversitesi" },
                new University { Id = 52, Name = "Fırat Üniversitesi" },
                new University { Id = 53, Name = "Galatasaray Üniversitesi" },
                new University { Id = 54, Name = "Gaziantep Üniversitesi" },
                new University { Id = 55, Name = "Gaziantep Bilim ve Teknoloji Üniversitesi" },
                new University { Id = 56, Name = "Gazi Üniversitesi" },
                new University { Id = 57, Name = "Gebze Teknik Üniversitesi" },
                new University { Id = 58, Name = "Giresun Üniversitesi" },
                new University { Id = 59, Name = "Gümüşhane Üniversitesi" },
                new University { Id = 60, Name = "Hacettepe Üniversitesi" },
                new University { Id = 61, Name = "Hakkari Üniversitesi" },
                new University { Id = 62, Name = "Harran Üniversitesi" },
                new University { Id = 63, Name = "Hitit Üniversitesi" },
                new University { Id = 64, Name = "Iğdır Üniversitesi" },
                new University { Id = 65, Name = "İnönü Üniversitesi" },
                new University { Id = 66, Name = "İstanbul Medeniyet Üniversitesi" },
                new University { Id = 67, Name = "İstanbul Sabahattin Zaim Üniversitesi" },
                new University { Id = 68, Name = "İstanbul Teknik Üniversitesi" },
                new University { Id = 69, Name = "İstanbul Ticaret Üniversitesi" },
                new University { Id = 70, Name = "İstanbul Üniversitesi" },
                new University { Id = 71, Name = "İstinye Üniversitesi" },
                new University { Id = 72, Name = "İzmir Bakırçay Üniversitesi" },
                new University { Id = 73, Name = "İzmir Demokrasi Üniversitesi" },
                new University { Id = 74, Name = "İzmir Ekonomi Üniversitesi" },
                new University { Id = 75, Name = "İzmir Kâtip Çelebi Üniversitesi" },
                new University { Id = 76, Name = "Kafkas Üniversitesi" },
                new University { Id = 77, Name = "Kahramanmaraş İstiklal Üniversitesi" },
                new University { Id = 78, Name = "Kahramanmaraş Sütçü İmam Üniversitesi" },
                new University { Id = 79, Name = "Karabük Üniversitesi" },
                new University { Id = 80, Name = "Karadeniz Teknik Üniversitesi" },
                new University { Id = 81, Name = "Karamanoğlu Mehmetbey Üniversitesi" },
                new University { Id = 82, Name = "Kastamonu Üniversitesi" },
                new University { Id = 83, Name = "Koç Üniversitesi" },
                new University { Id = 84, Name = "Konya Necmettin Erbakan Üniversitesi" },
                new University { Id = 85, Name = "KTO Karatay Üniversitesi" },
                new University { Id = 86, Name = "Malatya Turgut Özal Üniversitesi" },
                new University { Id = 87, Name = "Manisa Celal Bayar Üniversitesi" },
                new University { Id = 88, Name = "Mardin Artuklu Üniversitesi" },
                new University { Id = 89, Name = "Marmara Üniversitesi" },
                new University { Id = 90, Name = "Mehmet Akif Ersoy Üniversitesi" },
                new University { Id = 91, Name = "Mersin Üniversitesi" },
                new University { Id = 92, Name = "Mimar Sinan Güzel Sanatlar Üniversitesi" },
                new University { Id = 93, Name = "Muğla Sıtkı Koçman Üniversitesi" },
                new University { Id = 94, Name = "Muş Alparslan Üniversitesi" },
                new University { Id = 95, Name = "Namık Kemal Üniversitesi" },
                new University { Id = 96, Name = "Nevşehir Hacı Bektaş Veli Üniversitesi"},
                new University { Id = 97, Name = "Niğde Ömer Halisdemir Üniversitesi" },
                new University { Id = 98, Name = "Nuh Naci Yazgan Üniversitesi" },
                new University { Id = 99, Name = "Ordu Üniversitesi" },
                new University { Id = 100, Name = "Orta Doğu Teknik Üniversitesi" },
                new University { Id = 101, Name = "Osmaniye Korkut Ata Üniversitesi" },
                new University { Id = 102, Name = "Pamukkale Üniversitesi" },
                new University { Id = 103, Name = "Recep Tayyip Erdoğan Üniversitesi" },
                new University { Id = 104, Name = "Sakarya Üniversitesi" },
                new University { Id = 105, Name = "Selahaddin Eyyubi Üniversitesi" },
                new University { Id = 106, Name = "Siirt Üniversitesi" },
                new University { Id = 107, Name = "Sinop Üniversitesi" },
                new University { Id = 108, Name = "Sivas Cumhuriyet Üniversitesi" },
                new University { Id = 109, Name = "Süleyman Demirel Üniversitesi" },
                new University { Id = 110, Name = "Trakya Üniversitesi" },
                new University { Id = 111, Name = "Tunceli Üniversitesi" },
                new University { Id = 112, Name = "Uşak Üniversitesi" },
                new University { Id = 113, Name = "Yalova Üniversitesi" },
                new University { Id = 114, Name = "Yıldırım Beyazıt Üniversitesi" },
                new University { Id = 115, Name = "Yozgat Bozok Üniversitesi" },
                new University { Id = 116, Name = "Zonguldak Bülent Ecevit Üniversitesi" }
                );
        }
    }
}
